[[LLVM_full]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67dc50173e318bfa8c2ea719608421aab2f91fdf"
os = "windows"

    [[LLVM_full.download]]
    sha256 = "35385aaf822a7c8251a56d9e7e4a081ea4dc01e5f18ccb87220208db278fe3ed"
    url = "https://github.com/maleadt/LLVM_full.jl/releases/download/LLVM_full-v14.0.5+3/LLVM_full.v14.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
